import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { AuthForm } from '../components/AuthForm'
import { CreatePost } from '../components/CreatePost'
import styles from '../styles/Home.module.css'
import { useMe } from '../utils/hooks'

export default function Home() {
  const [loggedIn, setLoggedIn] = useState<boolean>(false)

  const { me } = useMe()

  useEffect(() => {
    if (me) {
      // we check if the query useMe() reutn empty object
      const isEmpty: boolean = Object.keys(me).length === 0
      isEmpty ? setLoggedIn(false) : setLoggedIn(true)
    }
  }, [me])

  //
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!loggedIn ? <AuthForm /> : <CreatePost />}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
